name: GitHub Environment Secret

on:
  workflow_dispatch:

jobs:
  
  deplyment:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://example.com
  
    steps:
      - name: Print Environment Secret
        run: echo "The secret value is ${{ secrets.APP_SECRET }}"
