# This is a basic workflow to help you get started with Actions

name: List All Default GitHub Variables

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    runs-on: ubuntu-latest
    steps:
      - run: env
    
  build-2:
    runs-on: windows-latest
    steps:
      - run: env
  
  build-3:
    runs-on: macos-latest
    steps:
      - run: env
    

