# This is a basic workflow to help you get started with Actions

name: List All Default GitHub Variables Demo 2

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print-values-of-env-vars
        run: 
          echo "$GITHUB_ENV"
          echo "$GITHUB_ACTION"
          echo "$GITHUB_API_URL"
          echo "$GITHUB_JOB"
          echo "$GITHUB_PATH"
          echo "$GITHUB_STEP_SUMMARY"
          echo "$GITHUB_WORKFLOW"
          echo "$GITHUB_REPOSITORY_OWNER"
          echo "$GITHUB_RUN_NUMBER"
          echo "$GITHUB_SERVER_URL"
          echo "$RUNNNER_NAME"
